# Generated by Django 5.2 on 2025-04-22 15:52

import autorizaciones.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('autorizaciones', '0002_alter_solicitud_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='persona',
            options={'verbose_name': 'Persona', 'verbose_name_plural': 'Personas'},
        ),
        migrations.AlterModelOptions(
            name='solicitud',
            options={'ordering': ['-fecha_creacion'], 'verbose_name': 'Solicitud de Compra', 'verbose_name_plural': 'Solicitudes de Compras'},
        ),
        migrations.AlterModelOptions(
            name='usuario',
            options={'permissions': [('puede_aprobar_solicitudes', 'Puede aprobar solicitudes de compra')], 'verbose_name': 'Usuario', 'verbose_name_plural': 'Usuarios'},
        ),
        migrations.RemoveField(
            model_name='persona',
            name='correo_secundario',
        ),
        migrations.AlterField(
            model_name='persona',
            name='rut',
            field=models.CharField(error_messages={'unique': 'Este RUT ya está registrado en el sistema'}, max_length=12, unique=True, validators=[autorizaciones.models.validar_rut], verbose_name='RUT'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='is_staff',
            field=models.BooleanField(default=False, verbose_name='Acceso Admin'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='autorizaciones.persona', verbose_name='Datos Personales'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='persona',
            index=models.Index(fields=['rut'], name='rut_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['estado'], name='estado_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitud',
            index=models.Index(fields=['fecha_creacion'], name='fecha_creacion_idx'),
        ),
        migrations.AlterModelTable(
            name='solicitud',
            table=None,
        ),
    ]
